### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by keyjm** [teaglebuilt/robotframework-seleniumproxy#6]
Seeing this error when trying to install the lib. I am on Python 3.6

`   Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hr/_brhrvds7lqgtcbhr71x5xf96008j9/T/pip-install-qb6vhm2_/robotframework-seleniumproxy/setup.py", line 1, in <module>
        import versioneer
    ModuleNotFoundError: No module named 'versioneer'
`

**Comment by teaglebuilt** [comment]
@keyjm i will bring out a new release for this. I am going to completely remove versioneer.

**Comment by nixuewei** [comment]
same issue even if install versioneer firstly
